'use client';

import { useState } from 'react';
import { BrainCircuit } from 'lucide-react';
import { Button } from '@/components/ui/button';
import {
  AlertDialog,
  AlertDialogAction,
  AlertDialogCancel,
  AlertDialogContent,
  AlertDialogDescription,
  AlertDialogFooter,
  AlertDialogHeader,
  AlertDialogTitle,
} from '@/components/ui/alert-dialog';
import { explainCasePriority } from '@/ai/flows/explain-case-priority';
import type { Case, DCA } from '@/lib/types';

type ExplainPriorityActionProps = {
  caseItem: Case;
  dca: DCA | undefined;
};

export function ExplainPriorityAction({ caseItem, dca }: ExplainPriorityActionProps) {
  const [isOpen, setIsOpen] = useState(false);
  const [isLoading, setIsLoading] = useState(false);
  const [explanation, setExplanation] = useState('');

  const handleExplain = async () => {
    setIsLoading(true);
    setExplanation('');
    try {
      const result = await explainCasePriority({
        debtAmount: caseItem.amount,
        aging: caseItem.aging,
        historicalDcaPerformance: dca?.recoveryRate || 50, // Default to 50% if no DCA
      });
      setExplanation(result.explanation);
    } catch (error) {
      console.error('Failed to get explanation:', error);
      setExplanation('Sorry, I was unable to generate an explanation at this time.');
    } finally {
      setIsLoading(false);
    }
  };

  return (
    <>
      <Button
        className="w-full justify-start"
        variant="outline"
        onClick={() => {
          setIsOpen(true);
          handleExplain();
        }}
        disabled={isLoading}
      >
        <BrainCircuit className="mr-2 h-4 w-4" />
        Explain Priority
      </Button>

      <AlertDialog open={isOpen} onOpenChange={setIsOpen}>
        <AlertDialogContent>
          <AlertDialogHeader>
            <AlertDialogTitle>AI Explanation for Priority Score: {caseItem.priorityScore}</AlertDialogTitle>
            <AlertDialogDescription>
              This explanation is generated by AI based on the case data.
            </AlertDialogDescription>
          </AlertDialogHeader>
          <div className="p-4 bg-muted/50 rounded-lg min-h-[100px]">
            {isLoading ? (
                <div className="flex items-center justify-center h-full">
                    <p className="text-sm text-muted-foreground animate-pulse">Generating explanation...</p>
                </div>
            ) : (
              <p className="text-sm">{explanation}</p>
            )}
          </div>
          <AlertDialogFooter>
            <AlertDialogCancel>Close</AlertDialogCancel>
          </AlertDialogFooter>
        </AlertDialogContent>
      </AlertDialog>
    </>
  );
}
